
[window]
decorations = "Buttonless"
opacity = 0.75
blur = true

  [window.padding]
  x = 10
  y = 10

[general]
import = [ "~/.config/alacritty/themes/siva.toml" ]

[selection]
save_to_clipboard = true

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Regular"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
style = "Italic"
